# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-02-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighterdb', '0012_auto_20170214_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fightermetric',
            old_name='code',
            new_name='hasher',
        ),
        migrations.RemoveField(
            model_name='fightmetric',
            name='event',
        ),
        migrations.AddField(
            model_name='fightmetric',
            name='event_hasher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fightmetric',
            name='fight_hasher',
            field=models.CharField(default=b'0', max_length=50, unique=True),
        ),
    ]
